export const GET_MISSIONS_SUCCESS = 'GET_MISSIONS_SUCCESS'
export const GET_MISSIONS_FAIL = 'GET_MISSIONS_FAIL'
export const GET_MISSION_DETAIL_SUCCESS = 'GET_MISSION_DETAIL_SUCCESS'
export const GET_MISSION_DETAIL_FAIL = 'GET_MISSION_DETAIL_FAIL'

export const SET_FAV_MISSION_SUCCESS = 'SET_FAV_MISSION_SUCCESS'
export const SET_FAV_MISSION_FAIL = 'SET_FAV_MISSION_FAIL'
export const SET_MISSION_DATE_RANGE = 'SET_MISSION_DATE_RANGE'
export const SET_MISSION_FILTERS = 'SET_MISSION_FILTERS'

export const RESET_MISSION_STATE = 'RESET_MISSION_STATE'

export const CREATE_MISSION_SUCCESS = 'CREATE_MISSION_SUCCESS'
export const CREATE_MISSION_FAIL = 'CREATE_MISSION_FAIL'