export const GET_DATA_LAYERS_SUCCESS = 'GET_DATA_LAYERS_SUCCESS'
export const GET_DATA_LAYERS_FAIL = 'GET_DATA_LAYERS_FAIL'
export const GET_DATA_LAYER_INFO_SUCCESS = 'GET_DATA_LAYER_INFO_SUCCESS'
export const GET_DATA_LAYER_INFO_FAIL = 'GET_DATA_LAYER_INFO_FAIL'

export const RESET_ALERT_STATE = 'RESET_ALERT_STATE'