export const GET_DATA_LAYERS_SUCCESS = 'GET_DATA_LAYERS_SUCCESS';
export const GET_DATA_LAYERS_FAIL = 'GET_DATA_LAYERS_FAIL';
export const GET_META_DATA_SUCCESS = 'GET_META_DATA_SUCCESS';
export const GET_META_DATA_FAIL = 'GET_META_DATA_FAIL';
export const META_DATA_LOADING = 'META_DATA_LOADING';
export const META_DATA_RESET = 'META_DATA_RESET';

export const GET_TIME_SERIES_SUCCESS = 'GET_TIME_SERIES_SUCCESS';
export const GET_FEATURE_INFO_SUCCESS = 'GET_FEATURE_INFO_SUCCESS';
export const GET_TIME_SERIES_FAIL = 'GET_TIME_SERIES_FAIL';

export const RESET_DATA_LAYER_STATE = 'RESET_DATA_LAYER_STATE';