export const GET_DATA_LAYERS_SUCCESS = 'GET_DATA_LAYERS_SUCCESS'
export const GET_DATA_LAYERS_FAIL = 'GET_DATA_LAYERS_FAIL'

export const GET_TIME_SERIES_SUCCESS = 'GET_TIME_SERIES_SUCCESS'
export const GET_TIME_SERIES_FAIL = 'GET_TIME_SERIES_FAIL'

export const RESET_DATA_LAYER_STATE = 'RESET_DATA_LAYER_STATE'