export const GET_COMMS_SUCCESS = 'GET_COMMS_SUCCESS'
export const GET_COMMS_FAIL = 'GET_COMMS_FAIL'
export const SET_COMMS_FILTERS = 'SET_COMMS_FILTERS'
export const RESET_COMMS_STATE = 'RESET_COMMS_STATE'
