export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_OAUTH2_SUCCESS = 'SIGN_UP_OAUTH2_SUCCESS';
export const SIGN_UP_OAUTH2_FAIL = 'SIGN_UP_OAUTH2_FAIL';
export const SIGN_UP_OAUTH2_REFRESH_SUCCESS = 'SIGN_UP_OAUTH2_REFRESH_SUCCESS';
export const SIGN_UP_OAUTH2_REFRESH_FAIL = 'SIGN_UP_OAUTH2_REFRESH_FAIL';
export const SIGN_OUT = 'SIGN_OUT';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const SET_AOI_SUCCESS = 'SET_AOI_SUCCESS';

export const CM_WIP = 'CM_WIP';
