export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL';
export const SET_PEOPLE_FILTERS = 'SET_PEOPLE_FILTERS';
export const RESET_PEOPLE_STATE = 'RESET_PEOPLE_STATE';
export const REFRESH_PEOPLE = 'REFRESH_PEOPLE';
