export const CM_GET_ORGLIST_SUCCESS = 'CM_GET_ORGLIST_SUCCESS'
export const CM_GET_ORGLIST_FAIL = 'CM_GET_ORGLIST_FAIL'
export const CM_GET_ROLELIST_SUCCESS = 'CM_GET_ROLELIST_SUCCESS'
export const CM_GET_ROLELIST_FAIL = 'CM_GET_ROLELIST_FAIL'
export const CM_WIP = 'CM_WIP'

