export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS'
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL'
export const SET_FAV_REPORT_SUCCESS = 'SET_FAV_REPORT_SUCCESS'
export const SET_FAV_REPORT_FAIL = 'SET_FAV_REPORT_FAIL'
export const SET_REPORT_DATE_RANGE = 'SET_REPORT_DATE_RANGE'
export const SET_REPORT_FILTERS = 'SET_REPORT_FILTERS'

export const RESET_REPORT_STATE = 'RESET_REPORT_STATE'
